
// beta 0.1.1k — Subclass mechanics/progression panels.
// This data is intentionally mechanical only: no roleplay themes or character fantasy.
const SUBCLASS_MECHANICS = {
  'Path of the World Tree (PHB 2024)': { levels:{3:[['Vitality of the Tree','Rage grants temporary Hit Points and improves your durability/resource support.']],6:[['Branches of the Tree','Use your subclass feature to reposition creatures in combat.']],10:[['Battering Roots','Improve reach/control while raging.']],14:[['Travel Along the Tree','Teleportation-style movement and positioning support.']] } },
  'Path of the Berserker (PHB 2024)': { levels:{3:[['Frenzy','Rage improves weapon damage output.']],6:[['Mindless Rage','Defensive protection against charm/frighten-style control while raging.']],10:[['Retaliation','Reaction-based damage when you are attacked.']],14:[['Intimidating Presence','Action-based control option against enemies.']] } },
  'Path of the Wild Heart (PHB 2024)': { levels:{3:[['Animal Speaker','Utility spell access.'],['Rage of the Wilds','Choose a combat adaptation while raging.']],6:[['Aspect of the Wilds','Choose an exploration/combat support adaptation.']],10:[['Nature Speaker','Additional utility spell access.']],14:[['Power of the Wilds','Additional combat adaptation while raging.']] } },
  'Path of the Zealot (PHB 2024)': { levels:{3:[['Divine Fury','First weapon hit on your turn deals extra damage while raging.']],6:[['Fanatical Focus','Reroll a failed saving throw while raging.']],10:[['Zealous Presence','Bonus Action team buff to attacks and saving throws.']],14:[['Rage beyond Death','Rage helps you continue fighting at 0 Hit Points.']] } },
  'Path of the Beast (Tasha)': { levels:{3:[['Form of the Beast','When you rage, choose a natural weapon option.']],6:[['Bestial Soul','Natural weapons become magical and gain movement/adaptation options.']],10:[['Infectious Fury','Force additional damage or reaction attacks through your natural weapons.']],14:[['Call the Hunt','Rage grants a team damage/survivability benefit.']] } },
  'Path of Wild Magic (Tasha)': { levels:{3:[['Magic Awareness','Detect nearby spells/magic effects.'],['Wild Surge','When you rage, roll for a magical combat effect.']],6:[['Bolstering Magic','Support attack rolls or restore spell slots.']],10:[['Unstable Backlash','Change wild surge effect when damaged or after a save trigger.']],14:[['Controlled Surge','Roll twice for Wild Surge and choose one result.']] } },
  'Path of the Ancestral Guardian (Xanathar)': { levels:{3:[['Ancestral Protectors','First target you hit while raging is hindered against your allies.']],6:[['Spirit Shield','Reaction reduces damage to an ally. Scaling: 2d6 at 6, 3d6 at 10, 4d6 at 14.']],10:[['Consult the Spirits','Utility divination features. Spirit Shield improves to 3d6.']],14:[['Vengeful Ancestors','Spirit Shield also returns force damage to the attacker. Spirit Shield improves to 4d6.']] } },
  'Path of the Storm Herald (Xanathar)': { levels:{3:[['Storm Aura','While raging, activate an aura effect as a Bonus Action. Damage/support scales by Barbarian level.']],6:[['Storm Soul','Gain resistance and environment benefits based on chosen storm.']],10:[['Shielding Storm','Extend your Storm Soul resistance to chosen creatures in your aura.']],14:[['Raging Storm','Your aura gains a reaction/control rider based on chosen storm.']] } },

  'College of Valor (PHB 2024)': { levels:{3:[['Combat Inspiration','Bardic Inspiration can improve ally damage or defense.'],['Martial Training','Improves armor/weapon combat options.']],6:[['Extra Attack','Attack twice when taking the Attack action.']],14:[['Battle Magic','Combine spellcasting with weapon attacks.']] } },
  'College of Dance (PHB 2024)': { levels:{3:[['Dazzling Footwork','Unarmed/mobility-based combat benefits.'],['Inspiring Movement','Bardic Inspiration can move allies without provoking.']],6:[['Tandem Footwork','Improve party Initiative.']],14:[['Leading Evasion','Evasion-style defense for you and nearby allies.']] } },
  'College of Lore (PHB 2024)': { levels:{3:[['Bonus Proficiencies','Gain additional skill proficiencies.'],['Cutting Words','Use Bardic Inspiration to reduce enemy rolls.']],6:[['Magical Discoveries','Add extra spells from any spell list.']],14:[['Peerless Skill','Use Bardic Inspiration on your own ability checks.']] } },
  'College of Glamour (PHB 2024)': { levels:{3:[['Mantle of Inspiration','Spend Bardic Inspiration to grant temporary Hit Points and movement.'],['Beguiling Magic','Gain charm/control spell support.']],6:[['Mantle of Majesty','Command-style Bonus Action control.']],14:[['Unbreakable Majesty','Defensive charm/control aura that punishes attackers.']] } },
  'College of Creation (Tasha)': { levels:{3:[['Mote of Potential','Bardic Inspiration gains additional effects.'],['Performance of Creation','Create a nonmagical object.']],6:[['Animating Performance','Animate an item as a combat companion.']],14:[['Creative Crescendo','Create more/larger objects with fewer limits.']] } },
  'College of Eloquence (Tasha)': { levels:{3:[['Silver Tongue','Reliable Persuasion/Deception checks.'],['Unsettling Words','Spend Bardic Inspiration to reduce a target saving throw.']],6:[['Unfailing Inspiration','Bardic Inspiration is not expended when it fails.'],['Universal Speech','Communicate across languages.']],14:[['Infectious Inspiration','After a Bardic Inspiration succeeds, grant another inspiration as a Reaction.']] } },
  'College of Swords (Xanathar)': { levels:{3:[['Bonus Proficiencies','Gain armor/weapon proficiency support.'],['Fighting Style','Choose Dueling or Two-Weapon Fighting.'],['Blade Flourish','Spend Bardic Inspiration for damage plus movement/defensive/control flourish.']],6:[['Extra Attack','Attack twice when taking the Attack action.']],14:[['Master’s Flourish','Use a d6 flourish without spending Bardic Inspiration.']] } },
  'College of Whispers (Xanathar)': { levels:{3:[['Psychic Blades','Spend Bardic Inspiration to add psychic damage on weapon hit.'],['Words of Terror','Out-of-combat fear setup.']],6:[['Mantle of Whispers','Steal a humanoid shadow to disguise and gain information.']],14:[['Shadow Lore','Magical secret that can charm/control a target.']] } },

  'Archfey Patron (PHB 2024)': { levels:{3:[['Expanded Spells','Add patron spells to your Warlock options.'],['Steps of the Fey','Teleportation-based defensive/mobility feature.']],6:[['Misty Escape','Reaction teleport/defense after taking damage.']],10:[['Beguiling Defenses','Defensive benefit against charm/control and reflected control.']],14:[['Bewitching Magic','Improve action economy after casting Enchantment/Illusion spells.']] } },
  'Celestial Patron (PHB 2024)': { levels:{3:[['Expanded Spells','Add patron spells to your Warlock options.'],['Healing Light','Gain a pool of d6s to heal as a Bonus Action. Pool scales with Warlock level.']],6:[['Radiant Soul','Improve radiant/fire damage and gain resistance support.']],10:[['Celestial Resilience','Grant temporary Hit Points after rests.']],14:[['Searing Vengeance','When near death, recover and damage/blind nearby enemies.']] } },
  'Great Old One Patron (PHB 2024)': { levels:{3:[['Expanded Spells','Add patron spells to your Warlock options.'],['Awakened Mind','Telepathic communication feature.'],['Psychic Spells','Psychic/mental spellcasting improvements.']],6:[['Clairvoyant Combatant','Mark a target for combat advantage and defensive benefits.']],10:[['Thought Shield','Psychic resistance and mental defense.']],14:[['Create Thrall','Long-term influence/control feature.']] } },
  'Fiend Patron (PHB 2024)': { levels:{3:[['Expanded Spells','Add patron spells to your Warlock options.'],['Dark One’s Blessing','Gain temporary Hit Points when you reduce a hostile creature to 0 HP.']],6:[['Dark One’s Own Luck','Add a d10 to an ability check or saving throw.']],10:[['Fiendish Resilience','Choose a damage resistance after a rest.']],14:[['Hurl Through Hell','Once per turn/rest cycle, banish and deal high psychic damage after a hit.']] } },
  'The Fathomless Patron (Tasha)': { levels:{3:[['Expanded Spells','Add patron spells to your Warlock options.'],['Tentacle of the Deeps','Bonus Action summon/attack tentacle; cold damage and speed reduction.'],['Gift of the Sea','Gain swim speed and underwater breathing.']],6:[['Oceanic Soul','Gain cold resistance and underwater communication.'],['Guardian Coil','Tentacle can reduce damage to you or an ally.']],10:[['Grasping Tentacles','Gain/empower control spell effect and temporary Hit Points.']],14:[['Fathomless Plunge','Teleport self and allies through water.']] } },
  'The Genie Patron (Tasha)': { levels:{3:[['Expanded Spells','Add patron spells based on genie kind.'],['Genie’s Vessel','Gain a vessel and add genie-type damage once per turn.']],6:[['Elemental Gift','Gain resistance and limited flight.']],10:[['Sanctuary Vessel','Allies can rest inside the vessel and gain healing benefits.']],14:[['Limited Wish','Replicate a lower-level spell effect without material components.']] } },
  'The Hexblade Patron (Xanathar)': { levels:{3:[['Expanded Spells','Add patron spells to your Warlock options.'],['Hexblade’s Curse','Curse a target for bonus damage, improved crit range, and healing on its death.'],['Hex Warrior','Use Charisma for one chosen weapon and gain armor/shield proficiency.']],6:[['Accursed Specter','Raise a slain humanoid as a specter ally.']],10:[['Armor of Hexes','Cursed target has a chance to miss you.']],14:[['Master of Hexes','Move Hexblade’s Curse to a new target after the cursed target dies.']] } },

  'War Domain (PHB 2024)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['War Priest','Bonus Action weapon attacks with limited uses.'],['Channel Divinity: Guided Strike','Add a large bonus to an attack roll.']],6:[['War God’s Blessing','Use Channel Divinity to improve ally attack roll.']],17:[['Avatar of Battle','Resistance to Bludgeoning, Piercing, and Slashing damage.']] } },
  'Light Domain (PHB 2024)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Warding Flare','Reaction imposes Disadvantage on an attack.'],['Channel Divinity: Radiance of the Dawn','Area radiant damage and dispel darkness.']],6:[['Improved Warding Flare','Protect allies with Warding Flare.']],17:[['Corona of Light','Aura improves radiant/fire damage and harms enemies.']] } },
  'Trickery Domain (PHB 2024)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Blessing of the Trickster','Grant stealth support.'],['Channel Divinity: Invoke Duplicity','Create a duplicate for positioning/spell delivery support.']],6:[['Trickster’s Transposition','Teleport/swap using your duplicate.']],17:[['Improved Duplicity','Duplicate feature improves with more options.']] } },
  'Life Domain (PHB 2024)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Disciple of Life','Healing spells restore extra Hit Points.'],['Channel Divinity: Preserve Life','Restore a pool of Hit Points to creatures.']],6:[['Blessed Healer','Healing others also heals you.']],17:[['Supreme Healing','Maximize healing dice.']] } },
  'Order Domain (Tasha)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Bonus Proficiencies','Gain armor/skill support.'],['Voice of Authority','When you target an ally with a spell, that ally can make a Reaction attack.']],6:[['Channel Divinity: Order’s Demand','Charm/control nearby creatures and force item drops.'],['Embodiment of the Law','Cast some enchantment spells as a Bonus Action.']],17:[['Order’s Wrath','Ally attacks against your marked target deal extra psychic damage.']] } },
  'Peace Domain (Tasha)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Emboldening Bond','Bond allies to add a d4 to attacks, saves, or checks.']],6:[['Channel Divinity: Balm of Peace','Move without provoking and heal creatures you pass.'],['Protective Bond','Bonded creatures can teleport and take damage for each other.']],17:[['Expansive Bond','Bond range and damage protection improve.']] } },
  'Twilight Domain (Tasha)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Eyes of Night','Long-range Darkvision sharing.'],['Vigilant Blessing','Grant Initiative advantage.']],6:[['Channel Divinity: Twilight Sanctuary','Aura grants temporary Hit Points or ends charm/frighten.'],['Steps of Night','Limited flight in dim light/darkness.']],17:[['Twilight Shroud','Twilight Sanctuary grants cover.']] } },
  'Forge Domain (Xanathar)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Bonus Proficiencies','Gain heavy armor and smith’s tools.'],['Blessing of the Forge','Improve one weapon or armor after a Long Rest.']],6:[['Soul of the Forge','Gain fire resistance and armor-based AC bonus.']],17:[['Saint of Forge and Fire','Fire immunity and resistance to nonmagical weapon damage while armored.']] } },
  'Grave Domain (Xanathar)': { levels:{3:[['Domain Spells','Always have domain spells prepared.'],['Circle of Mortality','Healing at 0 HP is maximized.'],['Eyes of the Grave','Detect undead.']],6:[['Channel Divinity: Path to the Grave','Mark a target to become vulnerable to next hit.'],['Sentinel at Death’s Door','Reaction can cancel a critical hit.']],17:[['Keeper of Souls','When enemies die nearby, heal an ally.']] } },

  'Circle of the Moon (PHB 2024)': { levels:{3:[['Circle Forms','Wild Shape supports stronger combat forms.'],['Circle Spells','Always prepared circle spells.']],6:[['Improved Circle Forms','Wild Shape combat scaling improves.']],10:[['Moonlight Step','Teleportation/mobility feature tied to Wild Shape/magic.']],14:[['Lunar Form','Wild Shape or circle form reaches final combat scaling.']] } },
  'Circle of the Land (PHB 2024)': { levels:{3:[['Circle Spells','Choose land type for always prepared spells.'],['Land’s Aid','Spend Wild Shape to heal allies and damage enemies.']],6:[['Natural Recovery','Recover spell slots with nature-linked rest feature.']],10:[['Nature’s Ward','Defensive resistance/immunity support.']],14:[['Nature’s Sanctuary','Defensive protection from beasts/plants and similar creatures.']] } },
  'Circle of Stars (PHB 2024)': { levels:{3:[['Star Map','Spellcasting focus and guiding spell support.'],['Starry Form','Spend Wild Shape for Archer, Chalice, or Dragon form benefits.']],6:[['Cosmic Omen','Roll omen after rest to help or hinder d20 rolls.']],10:[['Twinkling Constellations','Starry Form improvements.']],14:[['Full of Stars','Gain resistance while Starry Form is active.']] } },
  'Circle of the Sea (PHB 2024)': { levels:{3:[['Circle Spells','Always prepared sea-themed spells.'],['Wrath of the Sea','Spend Wild Shape to create an aura that damages/pushes enemies.']],6:[['Aquatic Affinity','Movement and environment support.']],10:[['Stormborn','Flight/resistance style improvement while Wrath is active.']],14:[['Oceanic Gift','Share Wrath of the Sea benefits with allies.']] } },
  'Circle of Spores (Tasha)': { levels:{3:[['Circle Spells','Always prepared circle spells.'],['Halo of Spores','Reaction necrotic damage.'],['Symbiotic Entity','Spend Wild Shape to gain temporary HP and improve spore/melee damage.']],6:[['Fungal Infestation','Animate a nearby corpse as a temporary creature.']],10:[['Spreading Spores','Create an area spore damage zone.']],14:[['Fungal Body','Gain immunities and critical hit protection.']] } },
  'Circle of Wildfire (Tasha)': { levels:{3:[['Circle Spells','Always prepared circle spells.'],['Summon Wildfire Spirit','Spend Wild Shape to summon a wildfire spirit for damage/teleport support.']],6:[['Enhanced Bond','Improve fire/healing spells while spirit is active.']],10:[['Cauterizing Flames','Create healing/damage flames when creatures die.']],14:[['Blazing Revival','Use your wildfire spirit to avoid dropping to 0 HP.']] } },
  'Circle of Dreams (Xanathar)': { levels:{3:[['Balm of the Summer Court','Pool of d6s heals and grants temporary HP. Pool scales with Druid level.']],6:[['Hearth of Moonlight and Shadow','Short-rest protection and stealth support.']],10:[['Hidden Paths','Bonus Action teleport self or ally.']],14:[['Walker in Dreams','Free limited teleportation/divination spell effects after rest.']] } },
  'Circle of the Shepherd (Xanathar)': { levels:{3:[['Speech of the Woods','Communication utility.'],['Spirit Totem','Summon spirit aura for healing, attack support, or temporary HP.']],6:[['Mighty Summoner','Summoned beasts/fey are tougher and count as magical.']],10:[['Guardian Spirit','Spirit Totem heals summoned creatures.']],14:[['Faithful Summons','When incapacitated/at 0 HP, summon beasts automatically.']] } },

  'Aberrant Sorcery (PHB 2024)': { levels:{3:[['Psionic Spells','Gain extra spells and replace them within rules.'],['Telepathic Speech','Telepathic communication feature.']],6:[['Psionic Sorcery','Cast psionic spells with Sorcery Points and no components.'],['Psychic Defenses','Gain psychic resistance and advantage vs charm/frighten.']],14:[['Revelation in Flesh','Spend Sorcery Points for mobility/senses/defense mutations.']],18:[['Warping Implosion','Teleport and pull creatures into an area burst.']] } },
  'Draconic Sorcery (PHB 2024)': { levels:{3:[['Draconic Resilience','Increase durability and natural armor style defense.'],['Draconic Spells','Gain subclass spell support.']],6:[['Elemental Affinity','Improve damage and resistance tied to chosen dragon type.']],14:[['Dragon Wings','Gain flight.']],18:[['Dragon Companion/Presence','High-level draconic combat feature.']] } },
  'Clockwork Sorcery (PHB 2024)': { levels:{3:[['Clockwork Spells','Gain extra spells and replace them within rules.'],['Restore Balance','Cancel Advantage/Disadvantage on a d20 roll.']],6:[['Bastion of Law','Spend Sorcery Points to create damage-reducing d8s.']],14:[['Trance of Order','Reliable rolls and enemy attack suppression.']],18:[['Clockwork Cavalcade','Restore creatures/repair/remove spell effects in an area.']] } },
  'Wild Magic Sorcery (PHB 2024)': { levels:{3:[['Wild Magic Surge','Chance to trigger magical surge after spellcasting.'],['Tides of Chaos','Gain Advantage and refresh through surges.']],6:[['Bend Luck','Spend Sorcery Points to modify another creature’s roll by 1d4.']],14:[['Controlled Chaos','Roll twice on Wild Magic Surge and choose.']],18:[['Spell Bombardment','Improve spell damage dice under specific roll conditions.']] } },
  'Divine Soul (Xanathar)': { levels:{3:[['Divine Magic','Access Cleric spell list for Sorcerer spell choices.'],['Favored by the Gods','Add 2d4 to a failed save or missed attack.']],6:[['Empowered Healing','Spend Sorcery Points to reroll healing dice.']],14:[['Otherworldly Wings','Gain flight.']],18:[['Unearthly Recovery','Bonus Action self-heal when below half HP.']] } },
  'Shadow Magic (Xanathar)': { levels:{3:[['Eyes of the Dark','Darkvision and Darkness spell support.'],['Strength of the Grave','Attempt to avoid dropping to 0 HP.']],6:[['Hound of Ill Omen','Spend Sorcery Points to summon a hound that hinders target saves.']],14:[['Shadow Walk','Teleport between dim/dark areas.']],18:[['Umbral Form','Spend Sorcery Points for resistance/incorporeal movement.']] } },
  'Storm Sorcery (Xanathar)': { levels:{3:[['Wind Speaker','Language/utility feature.'],['Tempestuous Magic','After casting a leveled spell, fly 10 feet without provoking.']],6:[['Heart of the Storm','Resistance and area damage after lightning/thunder spell.'],['Storm Guide','Weather utility.']],14:[['Storm’s Fury','Reaction damage and push when hit.']],18:[['Wind Soul','Lightning/thunder immunity and flight.']] } },

  'Fey Wanderer (PHB 2024)': { levels:{3:[['Dreadful Strikes','Weapon hits deal extra psychic damage.'],['Fey Wanderer Magic','Gain subclass spells.'],['Otherworldly Glamour','Wisdom improves Charisma checks and gain skill.']],7:[['Beguiling Twist','Reaction redirects charm/frighten failures.']],11:[['Fey Reinforcements','Summon Fey support.']],15:[['Misty Wanderer','Teleport uses and ally teleport support.']] } },
  'Hunter (PHB 2024)': { levels:{3:[['Hunter’s Prey','Choose damage/control benefit against targets.'],['Hunter’s Lore','Identify target weaknesses/resistances.']],7:[['Defensive Tactics','Choose a defensive combat option.']],11:[['Superior Hunter’s Prey','Improve offensive multi-target feature.']],15:[['Superior Hunter’s Defense','Improve defensive option.']] } },
  'Beast Master (PHB 2024)': { levels:{3:[['Primal Companion','Gain beast companion. Companion attacks/use scale with Proficiency Bonus and Ranger level.']],7:[['Exceptional Training','Companion actions and damage improve.']],11:[['Bestial Fury','Companion attacks more effectively.']],15:[['Share Spells','Spells you cast on yourself can also affect companion.']] } },
  'Gloom Stalker (PHB 2024)': { levels:{3:[['Dread Ambusher','Initiative and first-round attack/damage benefit.'],['Gloom Stalker Magic','Gain subclass spells.'],['Umbral Sight','Darkvision and darkness-based combat stealth.']],7:[['Iron Mind','Gain saving throw proficiency or improve mental defense.']],11:[['Stalker’s Flurry','Improve missed attacks.']],15:[['Shadowy Dodge','Reaction imposes Disadvantage on attacks against you.']] } },
  'Swarmkeeper (Tasha)': { levels:{3:[['Gathered Swarm','Once per turn, swarm adds damage, movement, or forced movement.'],['Swarmkeeper Magic','Gain subclass spells.']],7:[['Writhing Tide','Gain temporary flight/hover movement.']],11:[['Mighty Swarm','Gathered Swarm damage/control improves.']],15:[['Swarming Dispersal','Reaction resistance and teleport when taking damage.']] } },
  'Horizon Walker (Xanathar)': { levels:{3:[['Horizon Walker Magic','Gain subclass spells.'],['Detect Portal','Detect nearby planar portal.'],['Planar Warrior','Bonus Action converts next hit to force damage and adds damage.']],7:[['Ethereal Step','Cast Etherealness briefly as Bonus Action.']],11:[['Distant Strike','Teleport between attacks and make extra attack against different target.']],15:[['Spectral Defense','Reaction resistance to damage from one attack.']] } },
  'Monster Slayer (Xanathar)': { levels:{3:[['Monster Slayer Magic','Gain subclass spells.'],['Hunter’s Sense','Learn target immunities/resistances/vulnerabilities.'],['Slayer’s Prey','Bonus Action mark target for extra damage once per turn.']],7:[['Supernatural Defense','Add 1d6 to saves/checks against Slayer’s Prey.']],11:[['Magic-User’s Nemesis','Reaction interrupts spell/teleport.']],15:[['Slayer’s Counter','Reaction attack against Slayer’s Prey when it forces a save.']] } },

  'Champion (PHB 2024)': { levels:{3:[['Improved Critical','Weapon attacks score critical hits more often.'],['Remarkable Athlete','Improve physical checks and movement.']],7:[['Additional Fighting Style','Gain another Fighting Style.']],10:[['Heroic Warrior','Gain Heroic Inspiration in combat.']],15:[['Superior Critical','Critical range improves again.']],18:[['Survivor','Regain Hit Points at start of turn when below half.']] } },
  'Eldritch Knight (PHB 2024)': { levels:{3:[['Spellcasting','Gain Wizard spellcasting progression for the subclass.'],['Weapon Bond','Bond weapons and summon them.']],7:[['War Magic','Blend cantrips and weapon attacks.']],10:[['Eldritch Strike','Weapon hits impose Disadvantage on saves against your spells.']],15:[['Arcane Charge','Teleport when using Action Surge.']],18:[['Improved War Magic','Blend leveled spells and weapon attacks.']] } },
  'Psi Warrior (PHB 2024)': { levels:{3:[['Psionic Power','Gain Psionic Energy Dice. Dice size scales: d6 at 3, d8 at 5, d10 at 11, d12 at 17. Uses scale with proficiency/level rules.'],['Protective Field','Reaction reduces damage using Psionic Energy Die.'],['Psionic Strike','Add force damage after a weapon hit using Psionic Energy Die.'],['Telekinetic Movement','Move objects/creatures with psionic power.']],7:[['Psi-Powered Leap','Gain flying movement briefly.'],['Telekinetic Thrust','Psionic Strike can push or knock Prone.']],10:[['Guarded Mind','Resistance to psychic damage and end Charmed/Frightened.']],15:[['Bulwark of Force','Grant half cover to yourself/allies.']],18:[['Telekinetic Master','High-level telekinetic spell/effect access.']] } },
  'Battle Master (PHB 2024)': { levels:{3:[['Combat Superiority','Gain 4 Superiority Dice (d8) and learn 3 Maneuvers. Save DC uses Strength or Dexterity.'],['Maneuvers','Choose 3 Maneuvers now.'],['Student of War','Gain proficiency with one Artisan’s Tool.']],7:[['Know Your Enemy','Assess combat capabilities of a creature.'],['Combat Superiority Scaling','Superiority Dice: 5d8. Maneuvers Known: 5.']],10:[['Improved Combat Superiority','Superiority Dice become d10. Maneuvers Known: 7.']],15:[['Relentless','Regain one Superiority Die when rolling Initiative if you have none. Superiority Dice: 6d10. Maneuvers Known: 9.']],18:[['Improved Combat Superiority','Superiority Dice become d12. Superiority Dice: 6d12.']] } },
  'Rune Knight (Tasha)': { levels:{3:[['Bonus Proficiencies','Gain smith’s tools and Giant language.'],['Rune Carver','Learn 2 runes. Known runes scale: 2 at 3, 3 at 7, 4 at 10, 5 at 15.'],['Giant’s Might','Bonus Action grow, gain Advantage on Strength checks/saves, and add extra damage once per turn.']],7:[['Runic Shield','Reaction force attack reroll.'],['Rune Carver Scaling','Known Runes: 3.']],10:[['Great Stature','Extra Giant’s Might damage improves.'],['Rune Carver Scaling','Known Runes: 4.']],15:[['Master of Runes','Use each rune twice per rest. Known Runes: 5.']],18:[['Runic Juggernaut','Giant’s Might size/damage/reach improves.']] } },
  'Arcane Archer (Xanathar)': { levels:{3:[['Arcane Archer Lore','Gain skill/cantrip support.'],['Arcane Shot','Learn 2 Arcane Shot options. Uses: 2 per Short/Long Rest.']],7:[['Curving Shot','Bonus Action redirect missed magic arrow.'],['Magic Arrow','Arrows count as magical.']],10:[['Arcane Shot Improvement','Learn another Arcane Shot option.']],15:[['Ever-Ready Shot','Regain one Arcane Shot use when rolling Initiative if you have none.']],18:[['Arcane Shot Improvement','Arcane Shot damage improves.']] } },
  'Cavalier (Xanathar)': { levels:{3:[['Bonus Proficiency','Gain one skill or language.'],['Born to the Saddle','Mounted combat improvements.'],['Unwavering Mark','Mark enemies you hit; punish them if they attack others.']],7:[['Warding Maneuver','Reaction add d8 to AC and reduce damage.']],10:[['Hold the Line','Opportunity attacks stop movement.']],15:[['Ferocious Charger','Charge can knock target Prone.']],18:[['Vigilant Defender','Special reaction on every creature’s turn for opportunity attacks.']] } },
  'Samurai (Xanathar)': { levels:{3:[['Bonus Proficiency','Gain skill/language support.'],['Fighting Spirit','Bonus Action gain Advantage on weapon attacks and temporary HP. Uses per Long Rest.']],7:[['Elegant Courtier','Add Wisdom to Persuasion and gain saving throw proficiency.']],10:[['Tireless Spirit','Regain Fighting Spirit use when rolling Initiative if none.']],15:[['Rapid Strike','Trade Advantage on one attack for an additional attack.']],18:[['Strength before Death','Take an extra turn when reduced to 0 HP before falling unconscious.']] } },

  'Soulknife (PHB 2024)': { levels:{3:[['Psionic Power','Gain Psionic Energy Dice. Dice size scales with Rogue level.'],['Psychic Blades','Manifest psychic blades for attacks.']],9:[['Soul Blades','Improve Psychic Blades with accuracy/teleport options.']],13:[['Psychic Veil','Turn Invisible for a duration.']],17:[['Rend Mind','Stun/control a target damaged by Psychic Blades.']] } },
  'Assassin (PHB 2024)': { levels:{3:[['Assassinate','Improve Initiative and early-round damage.'],['Assassin’s Tools','Gain poison/disguise tool support.']],9:[['Infiltration Expertise','Create false identities.']],13:[['Envenom Weapons','Improve poison use/damage.']],17:[['Death Strike','High-damage opening strike against surprised/marked targets.']] } },
  'Thief (PHB 2024)': { levels:{3:[['Fast Hands','Use Cunning Strike/object options more efficiently.'],['Second-Story Work','Improve climbing and jumping.']],9:[['Supreme Sneak','Improve stealth while moving slowly.']],13:[['Use Magic Device','Use more magic items and attunement flexibility.']],17:[['Thief’s Reflexes','Gain an extra turn in the first round of combat.']] } },
  'Arcane Trickster (PHB 2024)': { levels:{3:[['Spellcasting','Gain Wizard spellcasting progression for the subclass.'],['Mage Hand Legerdemain','Mage Hand gains stealthy rogue utility.']],9:[['Magical Ambush','Hidden spellcasting imposes Disadvantage on saves.']],13:[['Versatile Trickster','Mage Hand helps grant Advantage.']],17:[['Spell Thief','Steal/disable a spell from another caster.']] } },
  'Phantom (Tasha)': { levels:{3:[['Whispers of the Dead','Gain floating skill/tool proficiency.'],['Wails from the Grave','After Sneak Attack, damage a second creature. Uses scale with Proficiency Bonus.']],9:[['Tokens of the Departed','Create soul trinkets to fuel features and gain defenses.']],13:[['Ghost Walk','Bonus Action spectral form with flight/defensive movement.']],17:[['Death’s Friend','Wails from the Grave improves and soul trinket generation improves.']] } },
  'Soulknife (Tasha)': { levels:{3:[['Psionic Power','Gain Psionic Energy Dice.'],['Psychic Blades','Manifest psychic blades for attacks.']],9:[['Soul Blades','Improve Psychic Blades with accuracy/teleport options.']],13:[['Psychic Veil','Turn Invisible for a duration.']],17:[['Rend Mind','Stun/control a target damaged by Psychic Blades.']] } },
  'Inquisitive (Xanathar)': { levels:{3:[['Ear for Deceit','Reliable Insight against lies.'],['Eye for Detail','Bonus Action Perception/Investigation.'],['Insightful Fighting','Bonus Action Insight check enables Sneak Attack without Advantage.']],9:[['Steady Eye','Advantage on Perception/Investigation if moving slowly.']],13:[['Unerring Eye','Detect illusions/shapechangers/deception.']],17:[['Eye for Weakness','Insightful Fighting adds extra Sneak Attack damage.']] } },
  'Mastermind (Xanathar)': { levels:{3:[['Master of Intrigue','Tool/language/disguise/mimicry support.'],['Master of Tactics','Help as Bonus Action at range.']],9:[['Insightful Manipulator','Learn comparative target capabilities.']],13:[['Misdirection','Redirect attacks to a creature providing cover.']],17:[['Soul of Deceit','Mental defense and truth magic resistance.']] } },
  'Scout (Xanathar)': { levels:{3:[['Skirmisher','Reaction move when enemy ends turn near you.'],['Survivalist','Gain Nature/Survival proficiency and Expertise.']],9:[['Superior Mobility','Increase Speed.']],13:[['Ambush Master','Initiative advantage and first-hit team attack support.']],17:[['Sudden Strike','Bonus Action extra attack and potential second Sneak Attack.']] } },
  'Swashbuckler (Xanathar)': { levels:{3:[['Fancy Footwork','Targets you attack cannot Opportunity Attack you that turn.'],['Rakish Audacity','Add Charisma to Initiative and enable one-on-one Sneak Attack.']],9:[['Panache','Social/combat taunt/charm feature.']],13:[['Elegant Maneuver','Bonus Action Advantage on Acrobatics/Athletics.']],17:[['Master Duelist','Reroll a missed attack with Advantage once per rest.']] } },

  'Abjurer (PHB 2024)': { levels:{3:[['Arcane Ward','Create a damage-absorbing ward when casting abjuration.'],['Abjuration Savant','Improve access/copying/preparation of abjuration spells.']],6:[['Projected Ward','Use ward to protect allies.']],10:[['Improved Abjuration','Improve abjuration spell checks.']],14:[['Spell Resistance','Advantage on spell saves and resistance to spell damage.']] } },
  'Diviner (PHB 2024)': { levels:{3:[['Portent','Roll d20s after Long Rest and replace later rolls.'],['Divination Savant','Improve access/copying/preparation of divination spells.']],6:[['Expert Divination','Recover lower-level spell slots after divination spells.']],10:[['The Third Eye','Gain special sight options.']],14:[['Greater Portent','Roll three Portent dice.']] } },
  'Evoker (PHB 2024)': { levels:{3:[['Sculpt Spells','Protect allies from your evocation spell areas.'],['Evocation Savant','Improve access/copying/preparation of evocation spells.']],6:[['Potent Cantrip','Damaging cantrips remain effective on successful saves.']],10:[['Empowered Evocation','Add Intelligence modifier to one damage roll of Wizard evocation spells.']],14:[['Overchannel','Maximize damage of lower-level Wizard spells with escalating cost.']] } },
  'Illusionist (PHB 2024)': { levels:{3:[['Improved Illusions','Improve Minor Illusion and illusion spell use.'],['Illusion Savant','Improve access/copying/preparation of illusion spells.']],6:[['Malleable Illusions','Change an active illusion.']],10:[['Illusory Self','Reaction causes an attack to miss.']],14:[['Illusory Reality','Make part of an illusion temporarily real.']] } },
  'Bladesinger (Tasha)': { levels:{3:[['Training in War and Song','Gain armor/weapon/performance support.'],['Bladesong','Bonus Action defensive/mobility/concentration boost. Uses scale with Proficiency Bonus.']],6:[['Extra Attack','Attack twice; one attack can be replaced with a cantrip.']],10:[['Song of Defense','Spend spell slot to reduce damage.']],14:[['Song of Victory','Add Intelligence modifier to melee weapon damage during Bladesong.']] } },
  'Order of Scribes (Tasha)': { levels:{3:[['Wizardly Quill','Magical quill improves spellbook work.'],['Awakened Spellbook','Spellbook becomes a magical focus and changes spell damage type.']],6:[['Manifest Mind','Create a spectral mind for sensing and spellcasting position.']],10:[['Master Scrivener','Create enhanced scrolls and reduce scroll cost.']],14:[['One with the Word','Use spellbook to avoid damage and lose spells temporarily.']] } },
  'War Magic (Xanathar)': { levels:{3:[['Arcane Deflection','Reaction bonus to AC or saving throw with spellcasting limit.'],['Tactical Wit','Add Intelligence modifier to Initiative.']],6:[['Power Surge','Store surges and add force damage to spells.']],10:[['Durable Magic','While concentrating, gain AC and saving throw bonuses.']],14:[['Deflecting Shroud','Arcane Deflection deals force damage to nearby enemies.']] } },

  'Warrior of the Open Hand (PHB 2024)': { levels:{3:[['Open Hand Technique','Flurry of Blows adds knock Prone, push, or reaction denial.']],6:[['Wholeness of Body','Self-healing feature.']],11:[['Fleet Step','Mobility/action economy improvement.']],17:[['Quivering Palm','Delayed high-damage strike using Focus.']] } },
  'Warrior of Mercy (PHB 2024)': { levels:{3:[['Hand of Healing','Spend Focus to heal with unarmed strike mechanics.'],['Hand of Harm','Spend Focus to add necrotic damage.']],6:[['Physician’s Touch','Healing removes conditions; harm can poison.']],11:[['Flurry of Healing and Harm','Apply healing/harm during Flurry more efficiently.']],17:[['Hand of Ultimate Mercy','Revive a dead creature.']] } },
  'Warrior of Shadow (PHB 2024)': { levels:{3:[['Shadow Arts','Spend Focus for darkness/stealth magic and darkvision support.']],6:[['Shadow Step','Teleport between dim/dark areas and gain attack advantage.']],11:[['Improved Shadow Step','Shadow teleport gains an attack/damage rider.']],17:[['Cloak of Shadows','Become Invisible in dim/darkness with combat benefits.']] } },
  'Warrior of the Elements (PHB 2024)': { levels:{3:[['Elemental Attunement','Unarmed strikes gain reach/damage type and elemental options.']],6:[['Environmental Burst','Area damage/control elemental feature.']],11:[['Stride of the Elements','Gain elemental movement such as flight/swim.']],17:[['Elemental Epitome','High-level elemental resistance and damage boost.']] } },
  'Way of the Astral Self (Tasha)': { levels:{3:[['Arms of the Astral Self','Spend Focus/Ki to summon astral arms with reach and Wisdom-based attacks.']],6:[['Visage of the Astral Self','Gain senses/communication benefits.']],11:[['Body of the Astral Self','Defensive/damage improvement while astral features active.']],17:[['Awakened Astral Self','Full form improves AC and attacks.']] } },
  'Way of the Drunken Master (Xanathar)': { levels:{3:[['Bonus Proficiencies','Gain Performance and brewer’s supplies.'],['Drunken Technique','Flurry of Blows grants Disengage and speed.']],6:[['Tipsy Sway','Stand from Prone cheaply and redirect missed attacks.']],11:[['Drunkard’s Luck','Cancel Disadvantage for Focus/Ki cost.']],17:[['Intoxicated Frenzy','Flurry can attack multiple creatures.']] } },
  'Way of the Kensei (Xanathar)': { levels:{3:[['Path of the Kensei','Choose kensei weapons and gain defensive/ranged attack options.']],6:[['One with the Blade','Kensei weapons count as magical and can spend Focus/Ki for extra damage.']],11:[['Sharpen the Blade','Spend Focus/Ki to add attack/damage bonus to kensei weapon.']],17:[['Unerring Accuracy','Reroll a missed kensei weapon attack once per turn.']] } },
  'Way of the Sun Soul (Xanathar)': { levels:{3:[['Radiant Sun Bolt','Ranged radiant spell attack using Monk combat scaling.']],6:[['Searing Arc Strike','Spend Focus/Ki to cast Burning Hands after Attack action.']],11:[['Searing Sunburst','Create radiant area burst with Focus/Ki scaling.']],17:[['Sun Shield','Emit light and deal radiant reaction damage.']] } },

  'Oath of Devotion (PHB 2024)': { levels:{3:[['Oath Spells','Always prepared oath spells.'],['Channel Divinity Options','Gain oath-specific Channel Divinity options for weapon accuracy/control.']],7:[['Aura of Devotion','Aura protects against charm.']],15:[['Smite of Protection','Smite grants defensive benefit.']],20:[['Holy Nimbus','Capstone aura damages enemies and improves defense.']] } },
  'Oath of Glory (PHB 2024)': { levels:{3:[['Oath Spells','Always prepared oath spells.'],['Channel Divinity Options','Athletic/mobility and smite support options.']],7:[['Aura of Alacrity','Increase movement speed for you and nearby allies.']],15:[['Glorious Defense','Reaction increases AC and can counterattack.']],20:[['Living Legend','Capstone improves Charisma checks, attack reliability, and defenses.']] } },
  'Oath of Vengeance (PHB 2024)': { levels:{3:[['Oath Spells','Always prepared oath spells.'],['Channel Divinity Options','Mark/control a target and gain attack advantage against it.']],7:[['Relentless Avenger','Move after Opportunity Attacks.']],15:[['Soul of Vengeance','Reaction attack against your marked target.']],20:[['Avenging Angel','Capstone flight and fear aura.']] } },
  'Oath of the Ancients (PHB 2024)': { levels:{3:[['Oath Spells','Always prepared oath spells.'],['Channel Divinity Options','Restraining/control and turning options.']],7:[['Aura of Warding','Resistance against spell damage for you and nearby allies.']],15:[['Undying Sentinel','Avoid dropping to 0 HP and age protections.']],20:[['Elder Champion','Capstone regeneration and improved spell/channel effects.']] } },
  'Oath of the Watchers (Tasha)': { levels:{3:[['Oath Spells','Always prepared oath spells.'],['Channel Divinity Options','Mental save support and turn extraplanar creatures.']],7:[['Aura of the Sentinel','Improve Initiative for you and nearby allies.']],15:[['Vigilant Rebuke','Reaction damage against creatures that force successful mental saves.']],20:[['Mortal Bulwark','Capstone truesight/advantage/banishment rider against extraplanar threats.']] } },
  'Oath of Conquest (Xanathar)': { levels:{3:[['Oath Spells','Always prepared oath spells.'],['Channel Divinity Options','Frighten nearby enemies or improve an attack roll.']],7:[['Aura of Conquest','Frightened enemies in aura have Speed 0 and take psychic damage.']],15:[['Scornful Rebuke','Attackers take psychic damage.']],20:[['Invincible Conqueror','Capstone resistance, extra attack, and improved criticals.']] } },
  'Oath of Redemption (Xanathar)': { levels:{3:[['Oath Spells','Always prepared oath spells.'],['Channel Divinity Options','Boost Persuasion or reflect attacker damage.']],7:[['Aura of the Guardian','Take damage for nearby allies as a Reaction.']],15:[['Protective Spirit','Regain Hit Points when below half.']],20:[['Emissary of Redemption','Resistance to creature damage and reflected radiant damage with restrictions.']] } }
};

function selectedSubclassName(classObj){
  if (!classObj) return '';
  return state.choices?.[`${classObj.id}|3|subclass|0`] || '';
}
function subclassMechanics(name){ return SUBCLASS_MECHANICS[name] || null; }
function subclassProgressionLevels(data){ return data ? Object.keys(data.levels||{}).map(Number).sort((a,b)=>a-b) : []; }
function createMechanicLines(entries){
  const ul=document.createElement('ul'); ul.className='featureDesc';
  (entries||[]).forEach(([name,desc])=>{
    const li=document.createElement('li');
    li.innerHTML = `<strong>${name}</strong>: ${desc}`;
    ul.appendChild(li);
  });
  return ul;
}
function renderSubclassProgressionPanel(name){
  const data = subclassMechanics(name);
  const panel=document.createElement('div'); panel.className='subclassProgressionPanel';
  if (!name || !data) return panel;
  const h=document.createElement('div'); h.className='subclassPanelTitle'; h.innerHTML=`<strong>${name}</strong> — Subclass Progression`; panel.appendChild(h);
  subclassProgressionLevels(data).forEach(lvl=>{
    const sec=document.createElement('div'); sec.className='subclassLevelPreview';
    sec.innerHTML = `<div class="subclassLevelTitle">Level ${lvl}</div>`;
    sec.appendChild(createMechanicLines(data.levels[lvl]));
    panel.appendChild(sec);
  });
  return panel;
}
function selectedSubclassFeaturesForLevel(classObj, lvl){
  const name = selectedSubclassName(classObj);
  const data = subclassMechanics(name);
  if (!data || !data.levels || !data.levels[lvl]) return [];
  return data.levels[lvl].map(([featureName, desc], idx)=>({
    id:`subclass_${classObj.id}_${lvl}_${idx}`,
    name: featureName,
    type:'subclassFeature',
    scope:'subclass',
    desc,
    subclassName:name
  }));
}
